app:
  name: "log_agent"
  mode: "develop"
  version: "v1.0.0"

log:
  level: "debug"
  type: "json"
  filename: "./log/log_agent.log"
  max_size: 200
  max_age: 30
  max_backups: 7

etcd:
  addr: "127.0.0.1:2379"
  collect_key: "collect_log_%s_conf"

kafka:
  addr: "192.168.99.100:9092"
  topic: "web_log"
  chan_size: 100000

nsq:
  addr: "127.0.0.1:4160"
  topic: "web_log"
  chan_size: 100000

influxDB:
  addr: "127.0.0.1:8086"
  username: "admin"
  password: "123456"
  database: "system_status"
  precision: "s"
